-- MySQL Script generated by MySQL Workbench
-- Thu Sep 27 10:04:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema2
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema university_core
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema university_core
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `university_core` DEFAULT CHARACTER SET latin1 ;
USE `university_core` ;

-- -----------------------------------------------------
-- Table `university_core`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_core`.`role` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `Ucreate` TINYINT(1) NOT NULL DEFAULT '0',
  `Uupdate` TINYINT(1) NOT NULL DEFAULT '0',
  `Udelete` TINYINT(1) NOT NULL DEFAULT '0',
  `Uselect` TINYINT(1) NOT NULL DEFAULT '0',
  `Ualter` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `university_core`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_core`.`users` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `profile_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `last_login` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `faild_login` INT(3) UNSIGNED NULL DEFAULT NULL,
  `lastupdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateby` VARCHAR(255) NULL DEFAULT NULL,
  `current_active` TINYINT(1) NOT NULL DEFAULT '0',
  `status` TINYINT(1) NOT NULL DEFAULT '0',
  `location` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `university_core`.`admission_apply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admission_apply` (
  `id` INT(10) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `s_f_name` VARCHAR(30) NOT NULL,
  `s_m_name` VARCHAR(30) NOT NULL,
  `s_l_name` VARCHAR(30) NOT NULL,
  `fathers_name` VARBINARY(50) NOT NULL,
  `mothers_name` VARBINARY(50) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `birth_date` DATE NOT NULL,
  `gender` VARCHAR(10) NULL,
  `admission_applycol` VARCHAR(45) NOT NULL,
  `marital_status` VARCHAR(20) NOT NULL,
  `country_id` INT NOT NULL,
  `national_id` VARCHAR(100) NOT NULL DEFAULT 0,
  `quota` VARCHAR(20) NULL DEFAULT 0,
  `scholarship` TINYINT NULL,
  `birth_place` VARCHAR(45) NULL DEFAULT 0,
  `c_date` TIMESTAMP NOT NULL,
  `admission_applycol3` VARCHAR(45) NULL
);
 


